"""initial_schema

Revision ID: fc00921950cc
Revises: 
Create Date: 2026-05-01 10:35:08.150356+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fc00921950cc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "insight_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("insight_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("core_thesis", sa.Text(), nullable=False),
        sa.Column("logic_chain", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("historical_insight", sa.Text(), nullable=True),
        sa.Column("sources", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("revision_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_insight_versions_insight_id"), "insight_versions", ["insight_id"], unique=False
    )
    op.create_table(
        "insights",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("core_thesis", sa.Text(), nullable=False),
        sa.Column("logic_chain", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("historical_insight", sa.Text(), nullable=True),
        sa.Column("sources", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("date_generated", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_insights_category"), "insights", ["category"], unique=False)
    op.create_index(
        op.f("ix_insights_date_generated"), "insights", ["date_generated"], unique=False
    )
    op.create_table(
        "token_usage_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model", sa.String(length=50), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("input_cost", sa.Float(), nullable=False),
        sa.Column("output_cost", sa.Float(), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_token_usage_records_model"), "token_usage_records", ["model"], unique=False
    )
    op.create_index(
        op.f("ix_token_usage_records_recorded_at"),
        "token_usage_records",
        ["recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_token_usage_records_total_cost"),
        "token_usage_records",
        ["total_cost"],
        unique=False,
    )
    op.create_table(
        "topic_insights",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("insight_id", sa.Integer(), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_topic_insights_insight_id"), "topic_insights", ["insight_id"], unique=False
    )
    op.create_index(
        op.f("ix_topic_insights_topic_id"), "topic_insights", ["topic_id"], unique=False
    )
    op.create_table(
        "topics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("keywords", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("last_fetched_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_topics_name"), "topics", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_topics_name"), table_name="topics")
    op.drop_table("topics")
    op.drop_index(op.f("ix_topic_insights_topic_id"), table_name="topic_insights")
    op.drop_index(op.f("ix_topic_insights_insight_id"), table_name="topic_insights")
    op.drop_table("topic_insights")
    op.drop_index(op.f("ix_token_usage_records_total_cost"), table_name="token_usage_records")
    op.drop_index(op.f("ix_token_usage_records_recorded_at"), table_name="token_usage_records")
    op.drop_index(op.f("ix_token_usage_records_model"), table_name="token_usage_records")
    op.drop_table("token_usage_records")
    op.drop_index(op.f("ix_insights_date_generated"), table_name="insights")
    op.drop_index(op.f("ix_insights_category"), table_name="insights")
    op.drop_table("insights")
    op.drop_index(op.f("ix_insight_versions_insight_id"), table_name="insight_versions")
    op.drop_table("insight_versions")
    # ### end Alembic commands ###
